config/routes.rb
Rails.application.routes.draw do
  resources :gossip do
    resources :comment
    resources :like, only: %i[new create destroy]
  end
  resources :user
  resources :city, only: [:show]
  resources :session, only: %i[new create destroy]
  root 'gossip#index'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get '/welcome/:name', to: 'gossip#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content,
            presence: true
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  validates :title,
            presence: true,
            length: { in: 3..14 }
  validates :content,
            presence: true
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :tags_gossips_connection, required: false
  has_many :gossips, through: :tags_gossips_connection
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 8 }

  validates :password_confirmation,
            presence: true
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @all_gossips = []
    @city = City.find(params['id'])
    City.all.each do |city|
      city.users.where(city_id: params[:id]).each do |user|
        user.gossips.each do |gossip|
          @all_gossips << gossip
        end
      end
    end
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  include SessionHelper
  before_action :authenticate_user, except: %i[index show]

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(content: params[:content], user: current_user, gossip_id: params[:gossip_id])

    flash[:notice] = 'Commentaire envoyé !' if @comment.save
    redirect_to gossip_path(@comment.gossip.id)
  end

  def edit
    @comment = Comment.find(params[:id])
    rights_user?(@comment)
  end

  def update
    @comment = Comment.find(params[:id])
    comment_params = params.permit(:content)
    if @comment.update(comment_params)
      flash[:notice] = 'Commentaire mis à jour !'
      redirect_to gossip_path(@comment.gossip.id)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  include SessionHelper
  before_action :authenticate_user, except: %i[index show]

  def welcome; end

  def index
    @gossip = Gossip.new
    @all_gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)

    if @gossip.save
      flash[:notice] = 'Gossip envoyé !'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
    rights_user?(@gossip)
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:notice] = 'Gossip mis à jour !'
      redirect_to gossip_path(@gossip.id)
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  include SessionHelper
  before_action :authenticate_user, only: %i[create destroy]

  def create
    @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id]) unless liked?
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @like = @gossip.likes.find(params[:id])
    @like.delete
    redirect_back(fallback_location: root_path)
  end

  private

  def liked?
    Like.where(gossip_id: params[:gossip_id], user_id: current_user.id).exists?
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  include SessionHelper

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      flash[:notice] = 'Connecté à une nouvelle session'
      log_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team; end

  def contact; end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include SessionHelper
  def new
    @user = User.new
  end

  def create
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description],
      age: params[:age],
      city: City.find(params[:city]),
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )

    if @user.save
      flash[:notice] = 'Compte créé avec succès !'
      log_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params['id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def rights_user?(object)
    redirect_to gossip_path(@comment.gossip.id) if current_user.id != object.user.id
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Please log in.'
      redirect_to new_session_path
    end
  end

  def authenticate_current_user
    unless current_user == Gossip.find(params[:id]).user || current_user == Comment.find(params[:id]).user
      redirect_to gossip_path(params[:id]), alert: 'Vous ne pouvez pas modifier ce potin/commentaire'
    end
  end

  def liked?(gossip, user)
    Like.where(gossip_id: gossip.id, user_id: user.id).exists?
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/city/show.html.erb
<h1>Gossips de <%= @city.name %></h1>
<div class="container">
  <div class="row">
    <div class="list-group list-group-flush">
      <% @all_gossips.each do |gossip| %>
        <div class="col col-lg-6">
            <%= link_to "/gossip/#{gossip.id}", :action => 'go' do %>
            <div class="list-group-item list-group-item-action">
              <p><b><%= gossip.user.first_name %> <%= gossip.user.last_name %></b> <small class="text-muted"><%= time_ago_in_words(gossip.created_at) %></small></p>
              <p class="h5"><%= gossip.title %></p>
              <p><%= gossip.content.truncate(100) %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to '← Retour', "javascript:history.back()", :class => 'btn btn-outline-dark btn-sm' %>
</div>

app/views/comment/edit.html.erb
<h1>Éditer un Commentaire</h1>

<% if @comment.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Le commentaire n’a pas pu être modifié pour la/les raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <div class="row">
    <%= form_tag url_for(action: 'update'), method: "put" do %>    
      <div class="form-group col col-lg-6">
          <%= text_area_tag 'content', @comment.content, class: 'form-control mb-3' %>
          <%= submit_tag "Mettre à jour le commentaire", class: 'btn btn-sm btn-dark' %>
      <% end %>
      <%= link_to "Effacer le commentaire", gossip_comment_url(@comment.id), method: :delete, class: 'btn btn-sm btn-dark' %><br/>
      <%= link_to '← Retour', "javascript:history.back()", :class => 'btn btn-outline-dark btn-sm mt-3' %>
      </div>
  </div>
</div>

app/views/comment/show.html.erb
<p><%= @comment.content %></p>

app/views/gossip/_form.html.erb
<div class="form-group col col-lg-6">
  <%= form_with(model: gossip) do |form| %>
    <%= form.text_field :title, :class => "form-control mb-3" %>
      <%= form.text_area :content, :class => "form-control mb-3" %>
      <%= form.submit %>
  <% end %>
</div>

app/views/gossip/edit.html.erb
<h1>Éditer un Gossip</h1>

<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Le Gossip n’a pas pu être modifié pour la/les raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <div class="row">
    <%= form_tag url_for(action: 'update'), method: "put" do %>    
      <div class="form-group col col-lg-6">
          <%= text_field_tag 'title', @gossip.title, class: 'form-control mb-3' %>
          <%= text_area_tag 'content', @gossip.content, class: 'form-control mb-3' %>
          <%= submit_tag "Mettre à jour le Gossip", class: 'btn btn-sm btn-dark' %>
    <% end %>
      </div>
  </div>
</div>

app/views/gossip/index.html.erb
<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Le Gossip n’a pas pu être créé pour la/les raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <div class="row">
  <h1 class="h4 mb-4">Accueil</h1>
    <div class="list-group list-group-flush">

  <% if User.find_by(id: session[:user_id]) %>

    <%= form_tag url_for(action: 'create'), method: "post" do %>    
      <div class="form-group col col-lg-6">
          <%= text_field_tag 'title', nil, placeholder: 'Titre', class: 'form-control mb-3' %>
          <%= text_area_tag 'content', nil, placeholder: "À quoi pensez-vous #{current_user.first_name} ?", class: 'form-control mb-3' %>
        <%= submit_tag "Envoyer", class: 'btn btn-sm btn-dark mb-5' %>
      </div>
    <% end %>


  <% end %>
      <% @all_gossips.order("updated_at","created_at").reverse.each do |gossip| %>
        <div class="col col-lg-6">
          <div class="list-group-item list-group-item-action">
            <%= link_to gossip_path(gossip.id), :class => 'listlink', :action => 'go' do %>
            <p><b><%= gossip.user.first_name %> <%= gossip.user.last_name %></b> <small class="text-muted"><%= time_ago_in_words(gossip.created_at) %> 
            <div>
            <% if gossip.updated_at > gossip.created_at %>
                · màj. <%= time_ago_in_words(gossip.updated_at) %>
              <% end %>
            </small></p>
            <p class="h5"><%= gossip.title %></p>
            <p><%= gossip.content.truncate(100) %></p>
          </div>
        <% end %>
        <p><%= link_to "#{gossip.comments.count} commentaires", gossip_path(gossip.id), :class => 'userlink' %> ·  
        <% if current_user && liked?(gossip, current_user) %>
          <%= link_to "#{gossip.likes.count} likes", gossip_like_path(gossip.id, Like.find_by(user_id: current_user.id, gossip_id: gossip.id)), method: "delete", :class => 'userlink' %></p>
        <% elsif current_user %>
          <%= link_to "#{gossip.likes.count} likes", gossip_like_index_path(gossip.id), method: "post", :class => 'userlink' %></p>
        <% else %>
          <%= link_to "#{gossip.likes.count} likes", nil, :class => 'userlink' %></p>
        <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  </div>

app/views/gossip/new.html.erb
<h1>Envoyer un nouveau Gossip</h1>

<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Le Gossip n’a pas pu être créé pour la/les raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <div class="row">
    <%= form_tag url_for(action: 'create'), method: "post" do %>    
      <div class="form-group col col-lg-6">
          <%= text_field_tag 'title', nil, placeholder: 'Titre', class: 'form-control mb-3' %>
          <%= text_area_tag 'content', nil, placeholder: "À quoi pensez-vous #{current_user.first_name} ?", class: 'form-control mb-3' %>
          <%= submit_tag "Envoyer le Gossip", class: 'btn btn-sm btn-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/gossip/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col col-lg-6 mt-3">
        <p><%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", "/user/#{@gossip.user.id}", :class => "userlink" %></p>
        <h1><%= @gossip.title %></h1>
        <p><%= @gossip.content %></p>
        <p class="text-mute"><small>Gossipé le <%= @gossip.created_at.to_s(:db) %> depuis <%= link_to @gossip.user.city.name, "/city/#{@gossip.user.city.id}" %></small></p>
        <% if @gossip.user == current_user %>
          <%= link_to "Éditer le Gossip", "/gossip/#{@gossip.id}/edit", class: 'btn btn-sm btn-dark' %>
          <%= link_to "Effacer le Gossip", @gossip, method: :delete, class: 'btn btn-sm btn-dark' %>
        <% end %>
      
        <% if current_user && liked?(@gossip, current_user) %>
          <%= link_to "#{@gossip.likes.count} likes", gossip_like_path(@gossip.id, Like.find_by(user_id: current_user.id, gossip_id: @gossip.id)), method: "delete", :class => 'btn btn-sm btn-success' %></p>
        <% elsif current_user %>
          <%= link_to "#{@gossip.likes.count} likes", gossip_like_index_path(@gossip.id), method: "post", :class => 'btn btn-sm btn-outline-dark' %></p>
        <% else %>
          <%= link_to "#{@gossip.likes.count} likes", nil, :class => 'btn btn-sm btn-outline-secondary' %></p>
        <% end %>
        <br/><%= link_to '← Retour', "javascript:history.back()", :class => 'btn btn-outline-dark btn-sm mt-3' %>

      <p class="text-muted mt-3"><%= @gossip.comments.count %> commentaires</p>

      <% if User.find_by(id: session[:user_id]) %>
        <%= form_tag url_for(controller: 'comment', gossip_id: @gossip.id, action: 'create'), method: "post" do %>    
          <div class="form-group">
          <%= text_area_tag 'content', nil, class: 'form-control mb-3' %>
          <%= submit_tag "Envoyer", class: 'btn btn-sm btn-dark mb-5' %>
      <% end %>

      </div>
      <% end %>

      <div class="list-group list-group-flush">
      <% @gossip.comments.order("updated_at","created_at").reverse.each do |comment| %>
        <%= link_to "/gossip/#{@gossip.id}/comment/#{comment.id}/edit", :class => 'listlink', :action => 'go' do %>
          <div class="list-group-item list-group-item-action">
            <p><b><%= comment.user.first_name %> <%= comment.user.last_name %></b> <small class="text-muted"><%= time_ago_in_words(comment.created_at) %>
              <% if comment.updated_at > comment.created_at %>
                  · màj. <%= time_ago_in_words(comment.updated_at) %>
                <% end %>
            </small></p>
            <p><%= comment.content %></p>
          </div>
        <% end %>
      <% end %> 
      </div>
      </div>
    </div>
</div>

app/views/gossip/welcome.html.erb
<div class="container">
    <h1>Bienvenue <%= params[:name] %></h1>
    <p>Ici c'est notre super site de potins, il est chouette, non ?</p>
</div>

app/views/user/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Création du compte impossible :</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row">
      <div class="form-group col col-lg-6">
        <p class="h4 mb-4">Créer un compte</p>
        <%= form_tag url_for(action: 'create'), method: "post" do %>    
          <div class="row">
            <%= label_tag 'Prénom', nil, class: 'col-sm-3' %>
            <%= text_field_tag 'first_name', nil, placeholder: 'Jean', class: 'form-control col mb-3' %>
          </div>

          <div class="row">
            <%= label_tag 'Nom', nil, class: 'col-sm-3' %>
            <%= text_field_tag 'last_name', nil, placeholder: 'Jeanjean', class: 'form-control col mb-3' %>
          </div>

          <div class="row">
            <%= label_tag 'Age', nil, class: 'col-sm-3' %>
            <%= text_field_tag 'age', nil, placeholder: '18', class: 'form-control col mb-3' %>
          </div>

          <div class="row">
            <%= label_tag 'Biographie', nil, class: 'col-sm-3' %>
            <%= text_area_tag 'description', nil, placeholder: 'Jeanjean', class: 'form-control col mb-3' %>
          </div>

          <div class="row">
            <%= label_tag 'Ville', nil, class: 'col-sm-3' %>
            <%= select_tag "city", options_from_collection_for_select(City.all, :id, :name), class: 'form-control col mb-3 form-select' %>
          </div>

          <div class="row">
            <%= label_tag 'email', nil, class: 'col-sm-3' %>
            <%= text_field_tag 'email', nil, placeholder: 'jean@internet.xyz', class: 'form-control col mb-3' %>
          </div>

          <div class="row">
            <%= label_tag 'Mot-de-passe', nil, class: 'col-sm-3' %>
            <%= password_field_tag 'password', @user.password, class: 'form-control col mb-3' %>
          </div>

          <div class="row">
            <%= label_tag 'Confirmation', nil, class: 'col-sm-3' %>
            <%= password_field_tag 'password_confirmation', @user.password, class: 'form-control col mb-3' %>
          </div>

            <%= submit_tag "Connexion", class: 'btn btn-sm btn-dark' %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<h1>À propos de <%= @user.first_name %> <%= @user.last_name %></h1>
  <div class="container">
    <div class="row">
          <div class="col col-lg-6 mt-3">
            <blockquote class="blockquote">
              <%= @user.description %>
            </blockquote>
            <dl class="row">
              <dt class="col-sm-3">Age</dt>
              <dd class="col-sm-9"><%= @user.age %></dd>
              <dt class="col-sm-3">Localisation</dt>
              <dd class="col-sm-9"><%= link_to "#{@user.city.name} (#{@user.city.zip_code})", "/city/#{@user.city.id}" %></dd>
              <dt class="col-sm-3">Email</dt>
              <dd class="col-sm-9"><%= mail_to @user.email, @user.email %></dd>
            </dl>
          </div>
      </div>
    </div>
    </div>

    
  <%= link_to '← Retour', "javascript:history.back()", :class => 'btn btn-outline-dark btn-sm' %>