config/routes.rb
Rails.application.routes.draw do
  resources :gossip do
    resources :comment
    resources :like, only: %i[new create destroy]
  end
  resources :user
  resources :city, only: [:show]
  resources :session, only: %i[new create destroy]
  root 'gossip#index'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get '/welcome/:name', to: 'gossip#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content,
            presence: true
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  validates :title,
            presence: true,
            length: { in: 3..14 }
  validates :content,
            presence: true
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :tags_gossips_connection, required: false
  has_many :gossips, through: :tags_gossips_connection
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 8 }

  validates :password_confirmation,
            presence: true
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @all_gossips = []
    @city = City.find(params['id'])
    City.all.each do |city|
      city.users.where(city_id: params[:id]).each do |user|
        user.gossips.each do |gossip|
          @all_gossips << gossip
        end
      end
    end
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  include SessionHelper
  before_action :authenticate_user, except: %i[index show]

  def welcome; end

  def index
    @gossip = Gossip.new
    @all_gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)

    if @gossip.save
      flash[:notice] = 'Gossip envoyé !'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
    rights_user?(@gossip)
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:notice] = 'Gossip mis à jour !'
      redirect_to gossip_path(@gossip.id)
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  include SessionHelper
  before_action :authenticate_user, only: %i[create destroy]

  def create
    @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id]) unless liked?
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @like = @gossip.likes.find(params[:id])
    @like.delete
    redirect_back(fallback_location: root_path)
  end

  private

  def liked?
    Like.where(gossip_id: params[:gossip_id], user_id: current_user.id).exists?
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include SessionHelper
  def new
    @user = User.new
  end

  def create
    @user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description],
      age: params[:age],
      city: City.find(params[:city]),
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )

    if @user.save
      flash[:notice] = 'Compte créé avec succès !'
      log_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params['id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def rights_user?(object)
    redirect_to gossip_path(@comment.gossip.id) if current_user.id != object.user.id
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Please log in.'
      redirect_to new_session_path
    end
  end

  def authenticate_current_user
    unless current_user == Gossip.find(params[:id]).user || current_user == Comment.find(params[:id]).user
      redirect_to gossip_path(params[:id]), alert: 'Vous ne pouvez pas modifier ce potin/commentaire'
    end
  end

  def liked?(gossip, user)
    Like.where(gossip_id: gossip.id, user_id: user.id).exists?
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/author/show.html.erb
<h1>À propos de <%= @author.first_name %> <%= @author.last_name %></h1>
  <div class="container">
    <div class="row">
          <div class="col col-lg-6 mt-3">
            <blockquote class="blockquote">
              <%= @author.description %>
            </blockquote>
            <dl class="row">
              <dt class="col-sm-3">Age</dt>
              <dd class="col-sm-9"><%= @author.age %></dd>
              <dt class="col-sm-3">Localisation</dt>
              <dd class="col-sm-9"><%= @author.city.name %> (<%= @author.city.zip_code %>).</dd>
              <dt class="col-sm-3">Email</dt>
              <dd class="col-sm-9"><%= mail_to @author.email, @author.email %></dd>
            </dl>
          </div>
      </div>
    </div>
    </div>

    
  <%= link_to '← Retour', "javascript:history.back()", :class => 'btn btn-outline-dark btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
          <%= link_to 'The Gossip Project', root_path, :class => 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to 'Team', team_path, :class => 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Contact', contact_path, :class => 'nav-link' %></li>
              <% if User.find_by(id: session[:user_id]) %>

                <li class="nav-item"><%= link_to 'Déconnexion', session_path(session.id), method: :delete, :class => 'nav-link' %></li>

              <% else %>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Compte</a>
                 <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                   <li><%= link_to 'Connexion', new_session_path, :class => 'dropdown-item' %></li>
                   <li><%= link_to 'Créer un compte', new_user_path, :class => 'dropdown-item' %></li>
                </ul>
                </li>
                </div>
              <% end %>
            </ul>
          </div>
        </nav>
          <% if alert %>
            <div class="alert alert-danger" role="alert">
              <%= alert %>
            </div>
          <% end %>
          <% if notice %>
            <div class="alert alert-success" role="alert">
              <%= notice %>
            </div>
          <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>